### PR TITLE
Add Unit Tilesets

### PR DESCRIPTION
**Pull request by RobLoach**
This adds a few of the unit tilesets for HexaRealm and FantaxyHex.

### CODE REVIEW

**Comment by yairm210** [comment]
Ideally we should not be getting game, game2 etc because this leads to more texture swapping - see [here](https://yairm210.github.io/Unciv/Modders/Images-and-Audio/#multiple-texture-atlases)
Please place these under Images.Tilesets instead of Images

**Comment by yairm210** [comment]
Actually checking the output I see this images are not the cause - we should probably split other images, such as construction icons, into different folders instead
This PR is good as is

**Comment by yairm210** [comment]
[Alpha frontier](https://github.com/carriontrooper/Alpha-Frontier) is a good example of a mod that splits its images to create more focused packed images, if you need an example

**Comment by RobLoach** [comment]
Having a Images.Tileset, along with splitting Building/Unit icons to Images.Constructions, results in the number of images going from 3 to 5. But I think the change makes sense.

**Comment by RobLoach** [comment]
Going to merge this for now. We can tweak the tileset setups afterwards. Down for any changes there.

**Pull request merged**
